# Generated by Django 2.1.5 on 2019-02-06 14:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgImage', models.ImageField(blank=True, null=True, upload_to='bg/', verbose_name='Arkaplan Resmi')),
                ('bgVideoMp4', models.FileField(blank=True, null=True, upload_to='bg/', verbose_name='Arkaplan Video(.mp4)')),
                ('bgVideoWebm', models.FileField(blank=True, null=True, upload_to='bg/', verbose_name='Arkaplan Video(.webm)')),
                ('bgVideoMobile', models.ImageField(blank=True, null=True, upload_to='bg/', verbose_name='Arkaplan Video(mobile)')),
                ('headerTop', models.TextField(max_length=400, verbose_name='Üst Başlık')),
                ('headerCenter', models.TextField(max_length=400, verbose_name='Ana Başlık')),
                ('headerBottom', ckeditor.fields.RichTextField()),
                ('buttonText', models.CharField(max_length=50, verbose_name='Buton Text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ana Sayfa',
                'verbose_name_plural': 'Ana Sayfa',
                'ordering': ['headerTop'],
            },
        ),
    ]
