# Generated by Django 2.1.5 on 2019-02-11 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', models.TextField(max_length=500, verbose_name='İçerik')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarihçe Başlık',
                'verbose_name_plural': 'Tarihçe Başlık',
            },
        ),
        migrations.CreateModel(
            name='HistoryYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='', verbose_name='Ikon', width_field=40)),
                ('year', models.PositiveIntegerField(verbose_name='Sene')),
                ('content', models.TextField(max_length=500, verbose_name='İçerik')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('historyHeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.HistoryHeader')),
            ],
            options={
                'verbose_name': 'Tarihçe İçerik',
                'verbose_name_plural': 'Tarihçe İçerik',
                'ordering': ['year'],
            },
        ),
    ]
