# Generated by Django 2.1.5 on 2019-02-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20190211_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyyears',
            options={'ordering': ['pk', 'year'], 'verbose_name': 'Tarihçe İçerik', 'verbose_name_plural': 'Tarihçe İçerik'},
        ),
    ]
